# Contexto de build: carpeta backend.
# Ejemplo: docker build -f documents/Dockerfile.test .

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY ["commons/Sidae.Commons.csproj", "commons/"]
COPY ["documents/Sidae.Documents/Sidae.Documents.csproj", "documents/Sidae.Documents/"]
RUN dotnet restore "documents/Sidae.Documents/Sidae.Documents.csproj"
COPY . .
RUN dotnet build "documents/Sidae.Documents/Sidae.Documents.csproj" -c Release -o /app/build

FROM build AS publish
WORKDIR "/src/documents/Sidae.Documents"
RUN dotnet publish "Sidae.Documents.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Sidae.Documents.dll"]
