<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>dc483863-f95f-4150-aaf7-6f937904b72o</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.6" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.5" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.5" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.5" />
		<PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" Version="10.0.5" />
		<PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" Version="10.0.5" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.1" />
		<PackageReference Include="Scalar.AspNetCore" Version="2.13.10" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="Sidae.Commons">
			<HintPath>Binaries\Sidae.Commons.dll</HintPath>
		</Reference>
	</ItemGroup>
</Project>
